FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /home/app
CMD ["mvn", "spring-boot:run"]

# FROM maven:3.9.6-eclipse-temurin-21 AS build
# WORKDIR /home/app
# COPY pom.xml ./
# RUN mvn dependency:go-offline
# COPY . .
# RUN mvn -f /home/app/pom.xml clean package -DskipTests

# FROM openjdk:21-jdk-slim
# COPY --from=build /home/app/target/*.jar /app.jar
# ENTRYPOINT ["sh","-c", "java -jar /app.jar"]
